import { RefObject } from '@mui/x-internals/types';
import * as React from 'react';
import {
  DataGridProcessedProps,
  GRID_ID_AUTOGENERATED,
  GridPipeProcessor,
  GridStateInitializer,
  useGridApiMethod,
  useGridRegisterPipeProcessor,
} from '../../../internals';
import { GridGroupNode } from '../../../models';
import { GridPrivateApiCommunity } from '../../../models/api/gridApiCommunity';
import { GRID_ROOT_GROUP_ID } from '../rows';
import {
  GridAggregationApi,
  GridAggregationModel,
  GridAggregationPrivateApi,
} from './gridAggregationInterfaces';
import { gridAggregationModelSelector } from './gridAggregationSelector';

export const GRID_ROOT_FOOTER_ID = 'auto-generated-group-footer-root';
const EMPTY_AGGREGATION_MODEL = {};

export const useGridAggregationStateInitializer: GridStateInitializer<
  Pick<DataGridProcessedProps, 'aggregationModel' | 'initialState'>
> = (state, props, apiRef) => {
  const model =
    props.aggregationModel ?? props.initialState?.aggregation?.model ?? EMPTY_AGGREGATION_MODEL;

  //TODO: add pinned row here instead of in the useGridRowPinning.ts
  return {
    ...state,
    aggregation: {
      model,
    },
  };
};

export const useGridAggregation = (
  apiRef: RefObject<GridPrivateApiCommunity>,
  props: Pick<
    DataGridProcessedProps,
    'aggregationModel' | 'onAggregationModelChange' | 'aggregationFunctions'
  >,
) => {
  apiRef.current.registerControlState({
    stateId: 'aggregation',
    propModel: props.aggregationModel,
    propOnChange: props.onAggregationModelChange,
    stateSelector: gridAggregationModelSelector,
    changeEvent: 'aggregationModelChange',
  });

  const setAggregationModel = React.useCallback(
    (model: GridAggregationModel) => {
      apiRef.current.setState((state) => ({
        ...state,
        aggregation: {
          ...state.aggregation,
          model,
        },
      }));
      apiRef.current.forceUpdate();
    },
    [apiRef],
  );

  const applyAggregation = React.useCallback(() => {
    const state = apiRef.current.state;
    const aggregationModel = state.aggregation.model;
    const aggregationFunctions = props.aggregationFunctions;

    if (!aggregationFunctions || !aggregationModel) {
      return;
    }

    const lookup = {};

    // Apply aggregation functions to each group
    for (const field in aggregationModel) {
      const aggregationFunctionName = aggregationModel[field];
      const aggregationFunction = aggregationFunctions.find(
        (func) => func.label === aggregationFunctionName,
      );

      if (!aggregationFunction) {
        continue;
      }

      const values = state.rows.ids.map((id) => state.rows.data[id][field]);
      const result = aggregationFunction.reduce({ values, groupId: GRID_ROOT_GROUP_ID, field });

      lookup[GRID_ROOT_GROUP_ID] = {
        ...lookup[GRID_ROOT_GROUP_ID],
        [field]: result,
      };
    }

    apiRef.current.setState((state) => ({
      ...state,
      aggregation: {
        ...state.aggregation,
        lookup,
      },
    }));
  }, [apiRef, props.aggregationFunctions]);

  const publicApi: GridAggregationApi = {
    setAggregationModel,
  };

  const privateApi: GridAggregationPrivateApi = {
    applyAggregation,
  };

  useGridApiMethod(apiRef, publicApi, 'public');
  useGridApiMethod(apiRef, privateApi, 'private');
};

export const useGridAggregationPreProcessors = (
  apiRef: RefObject<GridPrivateApiCommunity>,
  props: DataGridProcessedProps,
) => {
  const addTotalsRow = React.useCallback<GridPipeProcessor<'hydrateRows'>>(
    (params) => {
      params.tree[GRID_ROOT_FOOTER_ID] = {
        id: GRID_ROOT_FOOTER_ID,
        type: 'footer',
        depth: 0,
        parent: GRID_ROOT_GROUP_ID,
      };
      params.dataRowIdToModelLookup[GRID_ROOT_FOOTER_ID] = {
        id: GRID_ROOT_FOOTER_ID,
        [GRID_ID_AUTOGENERATED]: GRID_ROOT_FOOTER_ID,
      };
      (params.tree[GRID_ROOT_GROUP_ID] as GridGroupNode).footerId = GRID_ROOT_FOOTER_ID;

      return params;
    },
    [apiRef],
  );

  const addAggregationMenuItem = React.useCallback<GridPipeProcessor<'columnMenu'>>((items) => {
    return items.concat('aggregationMenu');
  }, []);

  const addGetCellParams = React.useCallback<GridPipeProcessor<'getCellParams'>>(
    (params) => {
      if (params.rowNode.type !== 'footer') {
        return params;
      }
      return {
        ...params,
        value: 'SUM',
        formattedValue: 'SUM',
        renderCell: undefined,
      };
    },
    [apiRef],
  );

  useGridRegisterPipeProcessor(apiRef, 'getCellParams', addGetCellParams);
  useGridRegisterPipeProcessor(apiRef, 'hydrateRows', addTotalsRow);
  useGridRegisterPipeProcessor(apiRef, 'columnMenu', addAggregationMenuItem);
};
