import { RefObject } from '@mui/x-internals/types';
import clsx from 'clsx';
import * as React from 'react';
import {
  DataGridProcessedProps,
  GRID_ID_AUTOGENERATED,
  GRID_ROW_GROUPING_SINGLE_GROUPING_FIELD,
  gridColumnLookupSelector,
  gridColumnVisibilityModelSelector,
  GridPipeProcessor,
  GridStateInitializer,
  useGridApiMethod,
  useGridApiOptionHandler,
  useGridRegisterPipeProcessor,
} from '../../../internals';
import { GridCellParams, GridGroupNode, GridRowId, GridValidRowModel } from '../../../models';
import { GridPrivateApiCommunity } from '../../../models/api/gridApiCommunity';
import { GRID_ROOT_GROUP_ID, gridRowsLookupSelector, gridRowTreeSelector } from '../rows';
import { defaultAggregationFunctions } from './defaultAggregationFunctions';
import {
  GridAggregationApi,
  GridAggregationFunction,
  GridAggregationModel,
  GridAggregationPrivateApi,
} from './gridAggregationInterfaces';
import {
  gridAggregationLookupSelector,
  gridAggregationModelSelector,
} from './gridAggregationSelector';

export const GRID_ROOT_FOOTER_ID = 'auto-generated-group-footer-root';
const EMPTY_AGGREGATION_MODEL = {};

export const gridAggregationStateInitializer: GridStateInitializer<
  Pick<DataGridProcessedProps, 'aggregationModel' | 'initialState'>
> = (state, props, apiRef) => {
  const model =
    props.aggregationModel ?? props.initialState?.aggregation?.model ?? EMPTY_AGGREGATION_MODEL;

  //TODO: add pinned row here instead of in the useGridRowPinning.ts
  return {
    ...state,
    aggregation: {
      model,
    },
  };
};

export const useGridAggregation = (
  apiRef: RefObject<GridPrivateApiCommunity>,
  props: Pick<
    DataGridProcessedProps,
    'aggregationModel' | 'onAggregationModelChange' | 'aggregationFunctions'
  >,
) => {
  apiRef.current.registerControlState({
    stateId: 'aggregation',
    propModel: props.aggregationModel,
    propOnChange: props.onAggregationModelChange,
    stateSelector: gridAggregationModelSelector,
    changeEvent: 'aggregationModelChange',
  });

  const setAggregationModel = React.useCallback(
    (model: GridAggregationModel) => {
      apiRef.current.setState((state) => ({
        ...state,
        aggregation: {
          ...state.aggregation,
          model,
        },
      }));
      apiRef.current.applyAggregation();
    },
    [apiRef],
  );

  const aggregationFunctions = React.useMemo(() => {
    return (
      props.aggregationFunctions ??
      (defaultAggregationFunctions as Record<string, GridAggregationFunction>)
    );
  }, [props.aggregationFunctions]);

  const setColumnAggregation = React.useCallback<GridAggregationApi['setColumnAggregation']>(
    (field, aggregation) => {
      setAggregationModel({
        ...gridAggregationModelSelector(apiRef.current.state),
        [field]: aggregation,
      });
    },
    [apiRef, setAggregationModel],
  );

  const getColumnAggregation = React.useCallback<GridAggregationApi['getColumnAggregation']>(
    (field) => {
      const model = gridAggregationModelSelector(apiRef.current.state);
      if (!model[field]) {
        return null;
      }
      const method = model[field];

      const aggFunc = aggregationFunctions[method];
      if (!aggFunc) {
        return null;
      }

      return {
        aggregation: model[field],
        function: {
          ...aggFunc,
          label: aggFunc.label,
          footerLabel: aggFunc.footerLabel ?? aggFunc.label,
        },
      };
    },
    [apiRef, aggregationFunctions],
  );

  const applyAggregation = React.useCallback(() => {
    const visibilityModel = gridColumnVisibilityModelSelector(apiRef.current.state);
    const aggregationModel = gridAggregationModelSelector(apiRef.current.state);
    const columnLookup = gridColumnLookupSelector(apiRef.current.state);

    if (!aggregationFunctions || !aggregationModel) {
      return;
    }

    const visibleAggregatedFields = Object.keys(aggregationModel).filter(
      (field) => visibilityModel[field] !== false,
    );

    if (!visibleAggregatedFields.length) {
      // hide the footer if there are no visible aggregated fields
      return;
    }
    const aggFuncMap = visibleAggregatedFields.reduce(
      (acc, field) => {
        const method = aggregationModel[field];
        if (!aggregationFunctions[method]) {
          throw new Error(`Aggregation function "${method}" not found`);
        }
        acc[field] = aggregationFunctions[method];

        return acc;
      },
      {} as Record<string, GridAggregationFunction>,
    );

    const postReduceFields = Object.entries(aggFuncMap).reduce(
      (acc, [field, func]) => (func.postReduce ? acc.concat(field) : acc),
      [] as string[],
    );

    const applyFields = Object.entries(aggFuncMap).reduce(
      (acc, [field, func]) => (func.apply ? acc.concat(field) : acc),
      [] as string[],
    );

    let hasApply = applyFields.length > 0;
    let hasPostReduce = postReduceFields.length > 0;

    const lookup = new Map<GridRowId, any>();
    const tree = gridRowTreeSelector(apiRef.current.state);
    const rowLookup = gridRowsLookupSelector(apiRef.current.state);
    function traverseAndAggregate(nodeId: GridRowId) {
      const node = tree[nodeId];
      if (node.type !== 'group') {
        throw new Error('Invalid node type');
      }

      const aggregatedData: Record<string, number> = {};
      const fieldValues: Record<string, any[]> = {};

      aggregatedData['count'] = 0;
      for (const field of visibleAggregatedFields) {
        aggregatedData[field] = 0;
      }

      // Aggregate child nodes
      for (const childNodeId of node.children) {
        const childType = tree[childNodeId].type;
        let row: GridValidRowModel | Record<string, any>;
        if (childType === 'group') {
          // first traverse the children
          const { aggregatedData: childAggregated, fieldValues: childFieldValues } =
            traverseAndAggregate(childNodeId);
          row = childAggregated;
          aggregatedData['count'] += row['count'];

          // Merge child field values into the current level
          const childFieldValuesKeys = Object.keys(childFieldValues);
          for (const field of childFieldValuesKeys) {
            fieldValues[field] ??= [];
            fieldValues[field].push(...childFieldValues[field]);
          }
        } else {
          row = rowLookup[childNodeId];
          aggregatedData['count'] += 1;
        }

        for (const field of visibleAggregatedFields) {
          // for leaf fields we may need to rely on valueGetters, for group fields we can use the row directly
          const value =
            childType === 'leaf'
              ? apiRef.current.getRowValue(row, columnLookup[field])
              : row[field];

          if (aggFuncMap[field].reduce) {
            const reducer = aggFuncMap[field].reduce;
            aggregatedData[field] = reducer(aggregatedData[field], value, {
              api: apiRef.current,
              field,
              row,
              rowNode: tree[childNodeId],
            });
          } else {
            if (childType === 'leaf') {
              fieldValues[field] ??= [];
              fieldValues[field].push(value);
            }
          }
        }
      }

      // Finalize average calculations
      const groupAggregatedData = {} as Record<string, number>;

      for (const field of postReduceFields) {
        if (aggFuncMap[field].postReduce) {
          groupAggregatedData[field] = aggFuncMap[field].postReduce(
            aggregatedData[field],
            {
              count: aggregatedData['count'],
            },
            {
              api: apiRef.current,
              field,
            },
          );
        }
      }

      for (const field of applyFields) {
        if (aggFuncMap[field].apply) {
          const values = fieldValues[field];
          aggregatedData[field] = aggFuncMap[field].apply(values, {
            api: apiRef.current,
            field,
          });
        }
      }

      // Store aggregated results in the group node
      if (hasPostReduce) {
        // if we have postReduce, then finalizations are done at the group level and can't be passed forward
        lookup.set(nodeId, { ...aggregatedData, ...groupAggregatedData });
      } else {
        lookup.set(nodeId, aggregatedData);
      }

      return {
        aggregatedData,
        fieldValues,
      };
    }
    traverseAndAggregate(GRID_ROOT_GROUP_ID);

    apiRef.current.setState((state) => ({
      ...state,
      aggregation: {
        ...state.aggregation,
        lookup,
      },
    }));
  }, [apiRef, aggregationFunctions]);

  const publicApi: GridAggregationApi = {
    setAggregationModel,
    setColumnAggregation,
    getColumnAggregation,
  };

  const privateApi: GridAggregationPrivateApi = {
    applyAggregation,
    aggregationFunctions,
  };

  useGridApiMethod(apiRef, publicApi, 'public');
  useGridApiMethod(apiRef, privateApi, 'private');
  useGridApiOptionHandler(apiRef, 'filteredRowsSet', applyAggregation);
};

export const useGridAggregationPreProcessors = (
  apiRef: RefObject<GridPrivateApiCommunity>,
  props: DataGridProcessedProps,
) => {
  const addTotalsRow = React.useCallback<GridPipeProcessor<'hydrateRows'>>(
    (params) => {
      params.tree[GRID_ROOT_FOOTER_ID] = {
        id: GRID_ROOT_FOOTER_ID,
        type: 'footer',
        depth: 0,
        parent: GRID_ROOT_GROUP_ID,
      };
      params.dataRowIdToModelLookup[GRID_ROOT_FOOTER_ID] = {
        id: GRID_ROOT_FOOTER_ID,
        [GRID_ID_AUTOGENERATED]: GRID_ROOT_FOOTER_ID,
      };
      (params.tree[GRID_ROOT_GROUP_ID] as GridGroupNode).footerId = GRID_ROOT_FOOTER_ID;

      return params;
    },
    [apiRef],
  );

  const addAggregationMenuItem = React.useCallback<GridPipeProcessor<'columnMenu'>>((items) => {
    return items.concat('columnMenuAggregationItem');
  }, []);

  const addGetCellParams = React.useCallback<GridPipeProcessor<'getCellParams'>>(
    (params) => {
      if (params.rowNode.type !== 'footer' && params.rowNode.type !== 'group') {
        return params;
      }
      const rowId = params.rowNode.type === 'footer' ? GRID_ROOT_GROUP_ID : params.id;
      const aggregation = apiRef.current.getColumnAggregation(params.field);
      if (!aggregation) {
        if (params.rowNode.type === 'footer') {
          if (params.field === GRID_ROW_GROUPING_SINGLE_GROUPING_FIELD) {
            return {
              ...params,
              colDef: {
                renderCell: undefined,
                cellClassName: clsx(params.colDef.cellClassName, 'font-medium tracking-wider'),
              },
              value: 'Total',
              formattedValue: undefined,
            } as GridCellParams<any, any, any, any>;
          }
          return {
            ...params,
            colDef: {
              renderCell: undefined,
            },
            value: undefined,
            formattedValue: undefined,
          } as GridCellParams<any, any, any, any>;
        }
        return params;
      }
      const lookup = gridAggregationLookupSelector(apiRef.current.state);
      const aggregatedValue = lookup.get(rowId)?.[params.field];

      const formattedValue =
        params.colDef.valueFormatter && aggregation.function.hasCellUnit !== false
          ? params.colDef.valueFormatter(
              aggregatedValue as never,
              {
                ...params.row,
                [params.field]: aggregatedValue,
                __aggregated__: true,
              },
              params.colDef,
              apiRef,
            )
          : aggregation.function.valueFormatter
            ? aggregation.function.valueFormatter(
                aggregatedValue as never,
                {
                  ...params.row,
                  [params.field]: aggregatedValue,
                },
                params.colDef,
                apiRef,
              )
            : aggregatedValue;
      return {
        ...params,
        colDef: {
          display: 'flex',
          align: 'left',

          renderCell: () => {
            return (
              <div
                className={clsx('aggregation-cell flex gap-2 w-full items-center justify-between')}
              >
                <props.slots.baseBadge data-variant="aggregation">
                  {aggregation.function.footerLabel}
                </props.slots.baseBadge>
                <div>{formattedValue}</div>
              </div>
            );
          },
        } as any,
        value: aggregatedValue,
        formattedValue,

        //formattedValue: 'SUM',
      } as GridCellParams<any, any, any, any>;
    },
    [apiRef, props.slots.baseBadge],
  );

  useGridRegisterPipeProcessor(apiRef, 'getCellParams', addGetCellParams);
  useGridRegisterPipeProcessor(apiRef, 'hydrateRows', addTotalsRow);
  useGridRegisterPipeProcessor(apiRef, 'columnMenu', addAggregationMenuItem);
};
