import * as Typescript from 'fumadocs-typescript';
import * as path from 'node:path';
import { rimraf } from 'rimraf';

const components = ['DataGrid'];
const interfaces = [
  'GridApi',
  // Params
  'GridColDef',
  'GridCellParams',
  'GridRowParams',
  'GridRowClassNameParams',
  'GridRowSpacingParams',
  'GridExportStateParams',

  // Filters
  'GridFilterModel',
  'GridFilterItem',
  'GridFilterOperator',

  // Others
  'GridSingleSelectColDef',
  'GridActionsColDef',
  'GridListColDef',

  // Aggregation
  'GridAggregationFunction',

  // Exporting
  'GridCsvExportOptions',
  'GridPrintExportOptions',
  'GridExcelExportOptions',
];

export async function generateDocs() {
  await rimraf('./content/docs/reference/(autogenerated)', {
    filter(v) {
      return !v.endsWith('index.mdx') && !v.endsWith('meta.json');
    },
  });

  const demoRegex = /^---type-table-demo---\r?\n(?<content>.+)\r?\n---end---$/gm;

  await Promise.all([
    Typescript.generateFiles({
      input: ['./content/docs/reference/(autogenerated)/*.model.mdx'],
      transformOutput(_, content) {
        return content.replace(demoRegex, '---type-table---\n$1\n---end---');
      },
      output: (file) =>
        path.resolve(path.dirname(file), `${path.basename(file).split('.')[0]}.mdx`),
    }),
  ]);
}
