import * as React from 'react';
import { GRID_ROW_GROUPING_SINGLE_GROUPING_FIELD } from '../../colDef/gridGroupingColumnColDef';
import { useThemedComponent } from '../../context/GridThemeContext';
import { gridRowMaximumTreeDepthSelector } from '../../hooks/features/rows/gridRowsSelector';
import { isAutogeneratedRowNode } from '../../hooks/features/rows/gridRowsUtils';
import { useGridApiContext } from '../../hooks/utils/useGridApiContext';
import { useGridRootProps } from '../../hooks/utils/useGridRootProps';
import { useGridSelector } from '../../hooks/utils/useGridSelector';
import type { GridColDef } from '../../models/colDef/gridColDef';
import type { GridRenderCellParams } from '../../models/params/gridCellParams';

interface GridBooleanCellProps extends GridRenderCellParams {
  hideDescendantCount?: boolean;
}

function GridBooleanCellRaw(props: GridBooleanCellProps) {
  const {
    id,
    value,
    formattedValue,
    api,
    field,
    row,
    rowNode,
    colDef,
    cellMode,
    isEditable,
    hasFocus,
    tabIndex,
    hideDescendantCount,
    ...other
  } = props;

  const apiRef = useGridApiContext();
  const rootProps = useGridRootProps();
  const classes = useThemedComponent('cell');

  const maxDepth = useGridSelector(apiRef, gridRowMaximumTreeDepthSelector);
  const isServerSideRowGroupingRow =
    // @ts-expect-error - Access tree data prop
    maxDepth > 0 && rowNode.type === 'group' && rootProps.treeData === false;

  const Icon = React.useMemo(
    () => (value ? rootProps.slots.booleanCellTrueIcon : rootProps.slots.booleanCellFalseIcon),
    [rootProps.slots.booleanCellFalseIcon, rootProps.slots.booleanCellTrueIcon, value],
  );

  if (isServerSideRowGroupingRow && value === undefined) {
    return null;
  }

  return (
    <Icon
      className={classes.variants.boolean}
      aria-label={apiRef.current.getLocaleText(
        value ? 'booleanCellTrueLabel' : 'booleanCellFalseLabel',
      )}
      data-value={Boolean(value)}
      {...other}
    />
  );
}

const GridBooleanCell = React.memo(GridBooleanCellRaw);

export { GridBooleanCell };

export const renderBooleanCell: GridColDef['renderCell'] = (params: GridBooleanCellProps) => {
  if (
    params.field !== GRID_ROW_GROUPING_SINGLE_GROUPING_FIELD &&
    isAutogeneratedRowNode(params.rowNode)
  ) {
    return '';
  }

  return <GridBooleanCell {...params} />;
};
